version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: user-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app
    command: go run main.go

volumes:
  db_data:
